# Generated by Django 4.2.7 on 2026-06-22 20:41

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymenttransaction_delete_payment'),
        ('hospitals', '0004_hospitalprofile_patients_treated_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HospitalPhoto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(blank=True, null=True, upload_to='hospital_photos/')),
                ('image_url', models.URLField(blank=True, null=True)),
                ('alt_text', models.CharField(blank=True, max_length=255)),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('display_order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('website_setup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hospital_photos', to='core.websitesetup')),
            ],
            options={
                'db_table': 'hospital_photos',
                'ordering': ['display_order', 'created_at'],
            },
        ),
    ]
