# Generated by Django 4.2.7 on 2026-06-24 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_businessinfo_years_of_experience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='websitesetup',
            name='plan_type',
            field=models.CharField(choices=[('BASIC', 'Basic'), ('STANDARD', 'Premium'), ('AI', 'AI'), ('PREMIUM', 'Premium')], default='BASIC', max_length=20),
        ),
    ]
