# Generated by Django 4.2.30 on 2026-07-02 18:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pharmacies', '0009_pharmacy_google_sheet_webhook_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='PharmacyStaff',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('pharmacy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='pharmacies.pharmacy')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='pharmacy_staff', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pharmacy Staff',
                'verbose_name_plural': 'Pharmacy Staff',
                'db_table': 'pharmacy_staff',
            },
        ),
    ]
