# Generated by Django 4.2.30 on 2026-07-02 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacies', '0010_pharmacystaff'),
    ]

    operations = [
        migrations.AddField(
            model_name='pharmacyorder',
            name='confirmation_email_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pharmacyorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
