# Generated by Django 4.2.7 on 2026-06-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_websitesetup_subscription_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='google_oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='is_onboarding_completed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='business_type',
            field=models.CharField(blank=True, choices=[('hospital', 'Hospital'), ('pharmacy', 'Pharmacy')], max_length=20),
        ),
    ]
