# Generated by Django 4.2.7 on 2026-06-23 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_paymenttransaction_delete_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessinfo',
            name='years_of_experience',
            field=models.IntegerField(blank=True, default=0, help_text='Years of business experience', null=True),
        ),
    ]
